In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## 얼굴사진, 탈과 거리

In [ ]:
from pandas import read_csv
df = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Standard_distance(수정후).csv")
df
#import pandas as pd
#sim = pd.read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/use_front_sim.csv")

filename     Boone   Yangban  \
0          use_front_cropped_Nathirah_Hussein_0001.jpg  4.332766  2.786860   
1    use_front_cropped_Nawabzada_Nasrullah_Khan_000...  3.943686  3.844432   
2    use_front_cropped_Newton_Carlton_Slawson_0001.jpg  4.650996  3.632902   
3           use_front_cropped_Nathalie_Gagnon_0001.jpg  1.505115  2.305420   
4           use_front_cropped_Natalie_Stewart_0001.jpg  7.014849  6.064289   
..                                                 ...       ...       ...   
607               use_front_cropped_Felix_Doh_0001.jpg  3.502731  2.390127   
608          use_front_cropped_Fayssal_Mekdad_0001.jpg  3.535707  2.193411   
609        use_front_cropped_Felipe_De_Borbon_0001.jpg  3.154135  1.633069   
610      use_front_cropped_Felipe_Perez_Roque_0001.jpg  4.339385  4.080114   
611           use_front_cropped_Faye_Alibocus_0001.jpg  2.759413  1.343406   

      Chorang     Halmi  
0    3.713573  3.703684  
1    3.904085  2.158160  
2    1.877964  2.980387  
3    4.096999  1.594307  
4    2.805345  5.336203  
..        ...       ...  
607  3.688814  2.997661  
608  3.363957  2.640642  
609  3.293896  1.072770  
610  1.918258  3.026783  
611  3.556398  2.078096  

[612 rows x 5 columns]

In [ ]:
df_val = df.drop(df.columns[[0]], axis=1)
simval = df_val.values
print(simval)

[[4.33276607 2.78686041 3.71357335 3.70368377]
 [3.94368569 3.84443219 3.90408496 2.15815996]
 [4.6509962  3.63290174 1.87796358 2.98038654]
 ...
 [3.15413519 1.6330685  3.29389583 1.0727702 ]
 [4.33938451 4.08011432 1.91825761 3.02678319]
 [2.75941278 1.34340596 3.55639794 2.07809604]]


## 가장 작은 거리 1번째, 2번째 탈

In [ ]:
#사람 사진 수(df의 row 수)
ren = 612

In [ ]:
import numpy as np
first = np.ones(ren, int)
for i in range(ren):
  first[i] = np.argmin(simval[i])

first

array([1, 3, 2, 0, 2, 3, 1, 1, 1, 2, 3, 2, 3, 1, 2, 3, 3, 3, 2, 3, 3, 0,
       1, 2, 3, 1, 3, 3, 1, 3, 0, 1, 1, 3, 3, 3, 3, 3, 3, 2, 1, 3, 3, 0,
       0, 3, 1, 1, 0, 2, 0, 0, 3, 2, 0, 3, 1, 3, 3, 3, 3, 1, 1, 3, 3, 1,
       3, 1, 3, 1, 0, 3, 3, 3, 1, 3, 0, 3, 1, 1, 3, 1, 3, 1, 3, 3, 3, 3,
       3, 3, 3, 1, 1, 3, 2, 1, 1, 3, 3, 1, 1, 1, 2, 1, 3, 2, 1, 0, 3, 1,
       2, 3, 1, 1, 1, 3, 3, 1, 1, 1, 1, 3, 3, 2, 1, 3, 0, 1, 1, 2, 3, 3,
       3, 0, 3, 3, 3, 0, 2, 3, 1, 0, 1, 1, 3, 3, 3, 3, 0, 3, 3, 3, 2, 3,
       1, 3, 1, 3, 3, 3, 3, 2, 3, 0, 1, 3, 2, 1, 3, 3, 3, 1, 3, 1, 3, 1,
       3, 2, 0, 1, 3, 1, 0, 1, 3, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3,
       2, 3, 1, 3, 1, 3, 3, 2, 3, 3, 1, 3, 1, 0, 1, 1, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 2, 3, 3, 3, 3, 1, 3, 3, 1, 3, 1, 3, 1, 3, 3, 3, 1, 3, 3,
       2, 3, 3, 1, 3, 3, 1, 1, 3, 3, 1, 1, 1, 3, 3, 3, 1, 2, 3, 0, 1, 3,
       1, 1, 1, 1, 3, 2, 2, 2, 1, 3, 3, 2, 1, 1, 3, 1, 2, 3, 1, 3, 1, 1,
       1, 1, 3, 3, 3, 0, 3, 1, 3, 3, 3, 3, 2, 0, 3,

In [ ]:
second = np.ones(ren, int)
for i in range(ren):
  sorted_dif_idx = np.argsort(simval[i])
  second[i] = sorted_dif_idx[1]
second

array([3, 1, 3, 3, 3, 0, 0, 3, 3, 3, 1, 3, 2, 3, 3, 1, 0, 1, 3, 2, 0, 1,
       0, 3, 0, 0, 1, 2, 3, 2, 3, 0, 3, 2, 1, 1, 2, 0, 1, 3, 3, 1, 0, 1,
       3, 1, 0, 0, 3, 3, 3, 1, 0, 3, 1, 1, 0, 0, 1, 1, 1, 0, 3, 2, 2, 2,
       2, 0, 2, 0, 3, 1, 2, 1, 0, 2, 1, 1, 0, 3, 0, 2, 2, 3, 2, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 3, 3, 3, 1, 1, 3, 3, 3, 3, 3, 2, 3, 0, 1, 1, 0,
       3, 0, 3, 0, 3, 1, 0, 3, 3, 0, 3, 1, 1, 3, 3, 0, 3, 3, 0, 3, 2, 1,
       2, 1, 1, 2, 2, 3, 3, 0, 3, 3, 0, 0, 0, 0, 0, 1, 3, 1, 1, 0, 3, 1,
       3, 0, 0, 0, 2, 0, 0, 1, 2, 1, 3, 1, 3, 3, 1, 1, 1, 3, 0, 0, 1, 3,
       1, 3, 3, 3, 0, 3, 1, 3, 2, 3, 1, 2, 1, 1, 2, 1, 2, 3, 1, 0, 1, 1,
       3, 2, 3, 2, 0, 0, 2, 3, 1, 2, 3, 1, 3, 1, 3, 0, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 3, 0, 2, 0, 2, 3, 2, 3, 1, 1, 2, 3, 2, 2,
       3, 1, 1, 3, 2, 1, 3, 3, 1, 0, 0, 0, 0, 2, 0, 1, 3, 3, 0, 1, 0, 2,
       3, 0, 3, 0, 0, 3, 1, 3, 3, 1, 2, 3, 3, 2, 0, 3, 3, 2, 0, 2, 0, 0,
       0, 0, 2, 1, 1, 3, 1, 3, 1, 2, 2, 2, 3, 1, 1,

In [ ]:
between = np.ones(ren)
near = np.zeros(ren, int)
for k in range(ren):
  idx1 = first[k]
  idx2 = second[k]
  between[k] = simval[k][idx2] - simval[k][idx1]
  if between[k] < 0.1:
    near[k] = 7

In [ ]:
simval[0][1] - simval[0][2]

-0.9267129368921898

In [ ]:
between

array([9.16823363e-01, 1.68627222e+00, 1.10242296e+00, 8.91919610e-02,
       2.53085780e+00, 9.82279800e-01, 1.15161573e+00, 9.29561464e-01,
       3.06614418e-01, 8.56210756e-02, 3.99567697e-01, 3.36660344e-01,
       1.19050409e+00, 2.10095612e-01, 5.59992994e-01, 1.98575939e-01,
       8.29007825e-01, 1.11423332e+00, 1.76508996e+00, 1.34967974e+00,
       1.69519750e+00, 1.92485873e-01, 1.93994580e+00, 4.98497406e-01,
       1.57403219e+00, 2.24622337e-01, 8.12991968e-01, 3.13934783e-01,
       9.49863346e-01, 1.09726440e+00, 6.40910092e-01, 1.53142411e+00,
       1.29485380e+00, 5.45142049e-01, 5.41677935e-01, 1.70459424e+00,
       1.22567266e+00, 8.69004069e-01, 2.07586749e+00, 5.82236995e-01,
       1.16220974e+00, 5.71166457e-01, 9.65657114e-01, 4.90806364e-01,
       7.48520067e-02, 1.17732185e+00, 1.24215841e+00, 6.38508100e-01,
       5.14713157e-02, 2.70844578e-01, 3.93197273e-02, 4.18812823e-01,
       1.16653364e+00, 4.62713353e-01, 5.09958637e-01, 4.42721564e-01,
      

In [ ]:
near

array([0, 0, 0, 7, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       7, 0, 0, 0, 7, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 7, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 7, 0, 7, 0, 0, 0, 7, 0, 0, 7, 0, 0, 0, 0, 0,
       0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 7, 0, 7, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

## 특성값, 거리값에 탈 라벨 추가

In [ ]:
df['first_tal'] = first
df['second_tal'] = second
df['between'] = between
df['near'] = near

In [ ]:
df2 = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/use_front_feature(수정후).csv")

In [ ]:
from pandas.io.formats.format import DataFrameFormatter
df2['first_tal'] = first
df2['second_tal'] = second


In [ ]:
#df2.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Label_612_Feature.csv", mode = 'a', index= False)
df.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Label_612_Distance.csv", mode = 'a', index= False)