In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
from scipy.spatial import distance

##1. 특성값 csv를 드라이브에서 불러오기

In [ ]:
#데이터 불러오기
import pandas as pd
dfren = pd.read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/원본1369장csv/Origin_feature_1369.csv")
filename = dfren['filename']
dfren = dfren.drop(dfren.columns[[0]], axis=1)
dfren = dfren.drop('filename', axis = 'columns')
dftal = pd.read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/tal_feature.csv")
dftal= dftal.drop(dftal.columns[[0]], axis=1)

In [ ]:
dfren

leye_ratio  reye_ratio  eye_angle  nose_ratio  chin_sharp
0       0.291087    0.277456  -0.959569    0.487660   -0.326441
1       0.312500    0.292103  -0.993151    0.499041   -0.549605
2       0.278733    0.264470  -0.998460    0.545455   -0.679607
3       0.333974    0.334489  -0.998460    0.657495   -0.752028
4       0.295075    0.295075  -0.993103    0.485714   -0.834348
...          ...         ...        ...         ...         ...
1364    0.324303    0.344495  -0.992667    0.546296   -0.564007
1365    0.278733    0.278733  -1.000000    0.575499   -0.773055
1366    0.221880    0.231714  -0.992907    0.595868   -0.601374
1367    0.236716    0.251455  -0.999993    0.602408   -0.778671
1368    0.333974    0.332443  -0.986228    0.459292   -0.501240

[1369 rows x 5 columns]

In [ ]:
dftal

leye_ratio  reye_ratio  eye_angle  nose_ratio  chin_sharp
0    0.147070    0.153448   0.614285    0.449289    0.402747
1    0.145130    0.152619   0.674302    1.125857    0.224951
2    0.866774    0.751130   0.489382    1.367977    0.111469
3    0.612834    0.559312   0.629320    0.863254    0.230050

### 사람수, 탈 수
rnum : 사람 수
tnum : 탈 수

In [ ]:
#df.shape[0] 행개수, df.shape[1] 열개수
rnum = dfren.shape[0]
tnum = dftal.shape[0]

#2. 특성값에 standard scaler 적용 / 이거씁니다.

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

scaler_S = StandardScaler()
ren_scaled_S = scaler_S.fit_transform(dfren)
tal_scaled_S = scaler_S.fit_transform(dftal)

dfren_scaled_S = pd.DataFrame(ren_scaled_S)
dftal_scaled_S = pd.DataFrame(tal_scaled_S)

In [ ]:
ren_scaled_S

array([[ 0.07087556, -0.14563255,  2.44147995, -1.12334757,  1.89654614],
       [ 0.3914285 ,  0.07170316, -0.2425882 , -0.98104848,  0.13249349],
       [-0.11405406, -0.33830799, -0.66697888, -0.40075202, -0.895146  ],
       ...,
       [-0.96514245, -0.8243474 , -0.22313496,  0.22955411, -0.27672843],
       [-0.74304965, -0.5314306 , -0.78950156,  0.31133114, -1.67821787],
       [ 0.71288824,  0.67026076,  0.31072342, -1.47802834,  0.51480139]])

In [ ]:
tal_scaled_S

array([[-0.95405008, -0.96381275,  0.18174909, -1.47504645,  1.54188054],
       [-0.96030463, -0.96700001,  1.05701399,  0.51173269, -0.16676575],
       [ 1.36658332,  1.334159  , -1.63977894,  1.22273074, -1.25734825],
       [ 0.54777139,  0.59665376,  0.40101586, -0.25941699, -0.11776654]])

In [ ]:
import pandas as pd
sim_S = pd.DataFrame(index = range(rnum), columns = ('Boone','Yangban', 'Choraeng', 'Halmi'))
from scipy.spatial import distance
for r in range(rnum):
  for t in range(tnum):
    sim_S.iloc[r][t] = distance.euclidean(ren_scaled_S[r], tal_scaled_S[t])

In [ ]:
sim_S.insert(0, 'filename', filename)

In [ ]:
sim_S

filename     Boone   Yangban  \
0           use_front_crop_Aaron_Eckhart_0001.jpg  2.660029  3.253531   
1           use_front_crop_Aaron_Peirsol_0001.jpg  2.300668  2.629259   
2     use_front_crop_Abdel_Nasser_Assidi_0001.jpg  2.985029  2.333819   
3            use_front_crop_Abdul_Rahman_0001.jpg  4.631699  3.237802   
4                use_front_crop_Abdullah_0001.jpg  4.002892  3.256357   
...                                           ...       ...       ...   
1364          use_front_crop_Zach_Parise_0001.jpg   3.04129  2.841172   
1365       use_front_crop_Zeljko_Rebraca_0001.jpg  3.812897  2.697104   
1366         use_front_crop_Zelma_Novelo_0001.jpg  2.529132  1.323205   
1367          use_front_crop_Zhang_Yimou_0001.jpg  3.838617  2.443602   
1368       use_front_crop_Zorica_Radovic_0001.jpg   2.55351  3.234321   

      Choraeng     Halmi  
0     5.998037  3.121817  
1      3.35934  1.139133  
2     2.950027  1.754159  
3     1.367049   2.14175  
4     3.366739  2.367684  
...        ...       ...  
1364   2.67661   0.68254  
1365  2.597547  2.175584  
1366  3.748465  2.227572  
1367  3.108332  2.667749  
1368  3.886792    1.3878  

[1369 rows x 5 columns]

In [ ]:
sim_S.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Origin_Distance.csv", mode = 'a', index = False)

##평균 차 거리.

In [ ]:
tal_mean = sim_S.mean(axis=0)
tal_mean

<ipython-input-20-2b372b0362ce>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  tal_mean = sim_S.mean(axis=0)


Boone      3.239927
Yangban    2.736968
Chorang    3.643564
Halmi      2.249139
dtype: float64

In [ ]:
tal_mean[0]

3.23992722222035

In [ ]:
sim_S.iloc[0][2]

3.253531394401344

In [ ]:
tal_mean[0] - sim_S.iloc[0][2]

-0.0136041721809943

In [ ]:
#데이터 프레임을 리스트로
sim_S_val = sim_S[["Boone","Yangban","Choraeng","Halmi"]].values.tolist()

In [ ]:
#평균보다 탈에 가까움 : 평균 - 자신 = 큼
import numpy as np
sub_val = np.zeros(rnum*tnum)
sub_val = sub_val.reshape(rnum,tnum)
for i in range(rnum):
  for t in range(tnum):
    sub_val[i][t] = tal_mean[t] - sim_S_val[i][t] #(뒤에가 작을수록) 값이 클 수록 더 닮았다.

sub_df = pd.DataFrame((sub_val), index = range(rnum), columns = ('Boone','Yangban', 'Chorang', 'Halmi'))
sub_df.insert(0, 'filename', filename)

In [ ]:
sub_val

array([[ 0.57989814, -0.51656381, -2.35447285, -0.87267842],
       [ 0.9392591 ,  0.10770832,  0.28422405,  1.11000576],
       [ 0.25489865,  0.40314857,  0.6935372 ,  0.49498005],
       ...,
       [ 0.71079567,  1.41376275, -0.10490079,  0.02156667],
       [-0.59868998,  0.29336607,  0.53523223, -0.41861039],
       [ 0.686417  , -0.49735298, -0.24322768,  0.86133853]])

In [ ]:
sub_df.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Origin_SubDistance.csv", mode = 'a', index = False)

##최소값 찾기 1. 거리 최솟값

In [ ]:
from pandas import read_csv
feature_df = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Origin_feature_1369.csv")

In [ ]:
#df에서 값만 빼냄
#df = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Origin_Distance.csv")
#df = df.drop(df.columns[[0]], axis=1)
#sim_S_val = df.values
#print(sim_S_val)

In [ ]:
import numpy as np
dmin = np.ones(rnum, int)
for i in range(rnum):
  dmin[i] = np.argmin(sim_S_val[i])
dmin

array([0, 3, 3, ..., 1, 1, 3])

In [ ]:
feature_df['distance_min'] = dmin

##최소값 찾기 2. 평균차 최댓값


In [ ]:
#평균차최솟값
#df2 = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Origin_SubDistance.csv")
#df2 = df2.drop(df.columns[[0]], axis=1)
#sub_val = df2.values
#print(sub_val)

In [ ]:
import numpy as np
smax = np.ones(rnum, int)
for i in range(rnum):
  smax[i] = np.argmax(sub_val[i])
smax

array([0, 3, 2, ..., 1, 2, 3])

In [ ]:
feature_df['sub_max'] = smax

In [ ]:
feature_df

Unnamed: 0                                     filename  leye_ratio  \
0              0        use_front_crop_Aaron_Eckhart_0001.jpg    0.291087   
1              1        use_front_crop_Aaron_Peirsol_0001.jpg    0.312500   
2              2  use_front_crop_Abdel_Nasser_Assidi_0001.jpg    0.278733   
3              3         use_front_crop_Abdul_Rahman_0001.jpg    0.333974   
4              4             use_front_crop_Abdullah_0001.jpg    0.295075   
...          ...                                          ...         ...   
1364        1374          use_front_crop_Zach_Parise_0001.jpg    0.324303   
1365        1375       use_front_crop_Zeljko_Rebraca_0001.jpg    0.278733   
1366        1376         use_front_crop_Zelma_Novelo_0001.jpg    0.221880   
1367        1377          use_front_crop_Zhang_Yimou_0001.jpg    0.236716   
1368        1378       use_front_crop_Zorica_Radovic_0001.jpg    0.333974   

      reye_ratio  eye_angle  nose_ratio  chin_sharp  distance_min  sub_max  
0       0.277456  -0.959569    0.487660   -0.326441             0        0  
1       0.292103  -0.993151    0.499041   -0.549605             3        3  
2       0.264470  -0.998460    0.545455   -0.679607             3        2  
3       0.334489  -0.998460    0.657495   -0.752028             2        2  
4       0.295075  -0.993103    0.485714   -0.834348             3        2  
...          ...        ...         ...         ...           ...      ...  
1364    0.344495  -0.992667    0.546296   -0.564007             3        3  
1365    0.278733  -1.000000    0.575499   -0.773055             3        2  
1366    0.231714  -0.992907    0.595868   -0.601374             1        1  
1367    0.251455  -0.999993    0.602408   -0.778671             1        2  
1368    0.332443  -0.986228    0.459292   -0.501240             3        3  

[1369 rows x 9 columns]

In [ ]:
##이거 또 돌리지 말기!(이미 있음)
feature_df.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/원본1369장csv/Origin_feature_label_1369.csv", mode = 'a', index = False)

##train_test data 라벨링
코드 설명: 파일이름에 포함된 인물이름이 같다면, 같은 라벨을 붙인다.<br>
블록1. printHumanName 인물이름만 출력 <br>
블록2.파일 이름과 파일 라벨 정보는 dataframe에 포함돼 있다. 불러옴.<br>
블록3.파일 이름 목록(name_list), 파일 라벨 목록(human_label) <br>
블록4-5. 파일 개수 확인(df.shape[0] 행 수(=파일수)를 센다.<br>
블록6.파일명 목록 > 인물 이름 목록 <br>
블록7. 라벨링할 전체 데이터의 파일이름을 불러온다.<br>

In [ ]:
import re
from pandas import read_csv
def printHumanName(string):
  #string = "use_front_crop_Aaron_Eckhart_0001_brightness_brightrange_1.jpg"
  try:
    found = re.search('crop_(.+?)_0001', string).group(1)
    return found
  except AttributeError:
    pass

In [ ]:
#필요한 표 불러오기
origin_name = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/원본1369장csv/Origin_Name.csv")
origin_df = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/원본1369장csv/Origin_feature_label_1369.csv")

In [ ]:
name_list = origin_name['name'].values
human_label = origin_df['sub_max'].values

In [ ]:
#두 길이, 사람 구성 같아야 함.
len(name_list)

1369

In [ ]:
len(human_label)

1369

In [ ]:
human_names = ['']*len(name_list)
for i in range(len(name_list)) :
  human_names[i] = printHumanName(name_list[i])

##15000장 라벨링
블록1. 탈 라벨열 생성(zero_tal, 0으로 초기화)(total: 전체 데이터수) <br>
블록2. 탈 라벨링:같은 인물 이름 포함시 같은 라벨을 적는다. <br>

In [ ]:
train_test_df = read_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Train_Test_feature.csv")
train_test_df = train_test_df.drop(train_test_df.columns[[0]], axis=1)
train_test_df

filename  leye_ratio  \
0                  use_front_crop_Aaron_Eckhart_0001.jpg    0.291087   
1         use_front_crop_Aaron_Eckhart_0001_blur45_0.jpg    0.293560   
2         use_front_crop_Aaron_Eckhart_0001_blur45_1.jpg    0.291087   
3      use_front_crop_Aaron_Eckhart_0001_brightness_b...    0.293560   
4      use_front_crop_Aaron_Eckhart_0001_brightness_b...    0.291087   
...                                                  ...         ...   
14625  use_front_crop_Zhang_Yimou_0001_brightness_dar...    0.249513   
14626  use_front_crop_Zhang_Yimou_0001_channel_shift_...    0.249513   
14627  use_front_crop_Zhang_Yimou_0001_channel_shift_...    0.280702   
14628      use_front_crop_Zhang_Yimou_0001_rotated_0.jpg    0.253280   
14629      use_front_crop_Zhang_Yimou_0001_rotated_1.jpg    0.280796   

       reye_ratio  eye_angle  nose_ratio  chin_sharp  
0        0.277456  -0.959569    0.487660   -0.326441  
1        0.277456  -0.974173    0.487660   -0.326441  
2        0.277456  -0.959569    0.487660   -0.362839  
3        0.277456  -0.974173    0.487660   -0.324620  
4        0.263017  -0.961180    0.487660   -0.382090  
...           ...        ...         ...         ...  
14625    0.249513  -1.000000    0.604326   -0.793794  
14626    0.250000  -0.998053    0.604326   -0.751361  
14627    0.280702  -1.000000    0.604326   -0.808646  
14628    0.272462  -0.998607    0.590810   -0.767949  
14629    0.280796  -1.000000    0.558062   -0.786151  

[14630 rows x 6 columns]

In [ ]:
train_test_df['filename'][train_test_df['filename'].isnull()]

Series([], Name: filename, dtype: object)

In [ ]:
train_test_df.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Train_Test_feature_reindex.csv")

In [ ]:
total = train_test_df.shape[0]

In [ ]:
total

14630

In [ ]:
total % 11

0

In [ ]:
total /11

1330.0

In [ ]:
TrainTest_list = train_test_df['filename'].values

In [ ]:
zero_tal = ['0'] * total
train_test_df['tal'] = zero_tal

In [ ]:
#15000장 라벨링
#k=0
#for t in range(total):
#  name = human_names[k]
#  while (name +'_0001' not in TrainTest_list[t]):
#    k+=1
#  train_test_df.iloc[t]['tal'] = human_label[k]


k = 0
for t in range(total):
    name = human_names[k]
    while name + '_0001' not in TrainTest_list[t]:
        k += 1
        name = human_names[k]  # 다음 인덱스의 이름을 확인

    train_test_df.at[t, 'tal'] = human_label[k]


In [ ]:
train_test_df['tal']

0        0
1        0
2        0
3        0
4        0
        ..
14625    2
14626    2
14627    2
14628    2
14629    2
Name: tal, Length: 14630, dtype: object

In [ ]:
train_test_df.to_csv("/content/drive/MyDrive/matlab 공모전/csv(표)/Train_Test_feature_label.csv")

In [ ]:
train_test_df['filename'][train_test_df['filename'].isnull()]

Series([], Name: filename, dtype: object)